// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetRepoById implements getRepoById operation.
//
// Gets a repository by its ID.
//
// GET /repos/{id}
func (UnimplementedHandler) GetRepoById(ctx context.Context, params GetRepoByIdParams) (r GetRepoByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRepoMedia implements getRepoMedia operation.
//
// Gets a repository by its ID and lists its media.
//
// GET /repos/{id}/media
func (UnimplementedHandler) GetRepoMedia(ctx context.Context, params GetRepoMediaParams) (r GetRepoMediaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRepoMediaById implements getRepoMediaById operation.
//
// Gets media by its ID in a repository.
//
// GET /repos/{repoId}/media/{mediaId}
func (UnimplementedHandler) GetRepoMediaById(ctx context.Context, params GetRepoMediaByIdParams) (r GetRepoMediaByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRepoMediaRawStream implements getRepoMediaRawStream operation.
//
// Gets media by its ID in a repository and returns an HTTP media stream of the original file.
//
// GET /repos/{repoId}/media/{mediaId}/stream/raw
func (UnimplementedHandler) GetRepoMediaRawStream(ctx context.Context, params GetRepoMediaRawStreamParams) (r GetRepoMediaRawStreamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRepos implements getRepos operation.
//
// Lists all repositories currently known to the server.
//
// GET /repos
func (UnimplementedHandler) GetRepos(ctx context.Context) (r []Repository, _ error) {
	return r, ht.ErrNotImplemented
}
