// Code generated by ogen, DO NOT EDIT.
package api

type GetRepoByIdRes interface {
	getRepoByIdRes()
}

type GetRepoMediaByIdRes interface {
	getRepoMediaByIdRes()
}

type GetRepoMediaRes interface {
	getRepoMediaRes()
}

type GetRepoMediaStreamRes interface {
	getRepoMediaStreamRes()
}
