// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"
)

// SetFake set fake values.
func (s *CastMember) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Role = "string"
		}
	}
	{
		{
			s.Image.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *EpisodeMetadata) SetFake() {
	{
		{
			s.Title = "string"
		}
	}
	{
		{
			s.OriginalTitle.SetFake()
		}
	}
	{
		{
			s.Overview.SetFake()
		}
	}
	{
		{
			s.ReleaseDate = time.Now()
		}
	}
	{
		{
			s.VoteRating = float64(0)
		}
	}
	{
		{
			s.Images = nil
			for i := 0; i < 0; i++ {
				var elem Image
				{
					elem.SetFake()
				}
				s.Images = append(s.Images, elem)
			}
		}
	}
	{
		{
			s.Series.SetFake()
		}
	}
	{
		{
			s.Season = int(0)
		}
	}
	{
		{
			s.Episode = int(0)
		}
	}
}

// SetFake set fake values.
func (s *Error) SetFake() {
	{
		{
			s.Description = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetRepoMediaOKApplicationJSON) SetFake() {
	var unwrapped []Media
	{
		unwrapped = nil
		for i := 0; i < 0; i++ {
			var elem Media
			{
				elem.SetFake()
			}
			unwrapped = append(unwrapped, elem)
		}
	}
	*s = GetRepoMediaOKApplicationJSON(unwrapped)
}

// SetFake set fake values.
func (s *Image) SetFake() {
	{
		{
			s.Path = "string"
		}
	}
	{
		{
			s.Remote = true
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Media) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Meta.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *MediaMeta) SetFake() {
	var variant EpisodeMetadata

	{
		variant.SetFake()
	}
	s.SetEpisodeMetadata(variant)
}

// SetFake set fake values.
func (s *Metadata) SetFake() {
	{
		{
			s.Title = "string"
		}
	}
	{
		{
			s.OriginalTitle.SetFake()
		}
	}
	{
		{
			s.Overview.SetFake()
		}
	}
	{
		{
			s.ReleaseDate = time.Now()
		}
	}
	{
		{
			s.VoteRating = float64(0)
		}
	}
	{
		{
			s.Images = nil
			for i := 0; i < 0; i++ {
				var elem Image
				{
					elem.SetFake()
				}
				s.Images = append(s.Images, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *MovieMetadata) SetFake() {
	{
		{
			s.Title = "string"
		}
	}
	{
		{
			s.OriginalTitle.SetFake()
		}
	}
	{
		{
			s.Overview.SetFake()
		}
	}
	{
		{
			s.ReleaseDate = time.Now()
		}
	}
	{
		{
			s.VoteRating = float64(0)
		}
	}
	{
		{
			s.Images = nil
			for i := 0; i < 0; i++ {
				var elem Image
				{
					elem.SetFake()
				}
				s.Images = append(s.Images, elem)
			}
		}
	}
	{
		{
			s.Genres = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Genres = append(s.Genres, elem)
			}
		}
	}
	{
		{
			s.Cast = nil
			for i := 0; i < 0; i++ {
				var elem CastMember
				{
					elem.SetFake()
				}
				s.Cast = append(s.Cast, elem)
			}
		}
	}
	{
		{
			s.Languages = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Languages = append(s.Languages, elem)
			}
		}
	}
	{
		{
			s.Countries = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Countries = append(s.Countries, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *NilMediaMeta) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilString) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *OptImage) SetFake() {
	var elem Image
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *Repository) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *SeriesMetadata) SetFake() {
	{
		{
			s.Title = "string"
		}
	}
	{
		{
			s.OriginalTitle.SetFake()
		}
	}
	{
		{
			s.Overview.SetFake()
		}
	}
	{
		{
			s.ReleaseDate = time.Now()
		}
	}
	{
		{
			s.VoteRating = float64(0)
		}
	}
	{
		{
			s.Images = nil
			for i := 0; i < 0; i++ {
				var elem Image
				{
					elem.SetFake()
				}
				s.Images = append(s.Images, elem)
			}
		}
	}
	{
		{
			s.Genres = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Genres = append(s.Genres, elem)
			}
		}
	}
	{
		{
			s.Cast = nil
			for i := 0; i < 0; i++ {
				var elem CastMember
				{
					elem.SetFake()
				}
				s.Cast = append(s.Cast, elem)
			}
		}
	}
	{
		{
			s.Languages = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Languages = append(s.Languages, elem)
			}
		}
	}
	{
		{
			s.Countries = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Countries = append(s.Countries, elem)
			}
		}
	}
}
