// Code generated by ogen, DO NOT EDIT.
package api

type GetRepoByIdRes interface {
	getRepoByIdRes()
}

type GetRepoMediaByIdRes interface {
	getRepoMediaByIdRes()
}

type GetRepoMediaRawStreamRes interface {
	getRepoMediaRawStreamRes()
}

type GetRepoMediaRes interface {
	getRepoMediaRes()
}
