[http]
host = ":8000"

[repos.test]
path = "./test-repo"
index_path = "./test-repo/.katana/index.json"
mux_cache_path = "./test-repo/.katana/mux_cache"
capabilities = ["watch"]

[repos.test.sources.analysis.literal]
